function createfigure(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 07-Jun-2021 14:07:34

% Create figure
figure('OuterPosition',[2368 254 616 493]);

% Create subplot
subplot1 = subplot(2,1,1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','o_{exp}','LineStyle','-.','Color',[1 0 0]);
set(plot1(2),'DisplayName','o_{model}','Color',[1 0 0]);
set(plot1(3),'DisplayName','s_{exp}','LineStyle','-.','Color',[0 0 1]);
set(plot1(4),'DisplayName','s_{model}','Color',[0 0 1]);

% Create title
title('Forward Kinematics Performance');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 0.3]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',14,'FontWeight','bold');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Orientation','horizontal');

% Create subplot
subplot2 = subplot(2,1,2);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'LineWidth',2,'Color',[0 0 0]);
set(plot2(1),'DisplayName','o','LineStyle','-.');
set(plot2(2),'DisplayName','s');

% Create title
title('Normalized Error ||e||/L');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 0.04]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',14,'FontWeight','bold');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Orientation','horizontal');

